resources:
  repositories:
    - repository: templates
      type: github
      endpoint: github
      name: ccdc-opensource/conan-azure-devops
      ref: refs/heads/development

extends:
  template: third-party-library-all-platforms-from-conan-center.yml@templates
  parameters:
    package: pixman
    package_version: 0.42.2
    source_repository: public-conan-center
    destination_repository: ccdc-3rdparty-conan
    build_types:
      - Release
      - Debug
